services:
  backend:
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app/backend
          ignore:
            - ./backend/node_modules/
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 1234:1234

  frontend:
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - ./frontend/node_modules/
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 5173:5173
